# Generated by Django 5.2.16 on 2026-07-22 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Контрагент (как в 1С)')),
                ('channel', models.CharField(choices=[('сети', 'Сети'), ('e-com', 'E-com'), ('опт', 'Опт'), ('экспорт', 'Экспорт'), ('horeca', 'HoReCa'), ('стм', 'СТМ'), ('прочее', 'Прочее')], default='прочее', max_length=10, verbose_name='Канал')),
                ('credit_limit', models.BigIntegerField(blank=True, null=True, verbose_name='Кредитный лимит')),
                ('excluded', models.BooleanField(default=False, verbose_name='Исключить из аналитики')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Справочник клиентов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkuMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255, unique=True, verbose_name='Карточка 1С')),
                ('real_sku', models.CharField(blank=True, max_length=255, verbose_name='Реальный SKU')),
                ('line', models.CharField(blank=True, max_length=100, verbose_name='Линейка')),
                ('brand_type', models.CharField(choices=[('own', 'Свой бренд'), ('private_label', 'СТМ'), ('non_product', 'Непродуктовое')], default='own', max_length=15, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'Справочник номенклатуры',
                'ordering': ['raw_name'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sales_client', 'Продажи по контрагентам'), ('sales_sku', 'Продажи по номенклатуре'), ('debt', 'Дебиторка')], max_length=20, verbose_name='Тип отчёта')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хеш файла')),
                ('period_year', models.IntegerField(blank=True, null=True, verbose_name='Год данных')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('rows_loaded', models.IntegerField(default=0, verbose_name='Строк загружено')),
                ('control_sum', models.BigIntegerField(default=0, verbose_name='Контрольная сумма')),
                ('status', models.CharField(default='ok', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Загрузка',
                'verbose_name_plural': 'Загрузки данных',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SkuFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_raw', models.CharField(db_index=True, max_length=255, verbose_name='Карточка 1С')),
                ('brand_type', models.CharField(default='own', max_length=15, verbose_name='Тип')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField()),
                ('qty', models.FloatField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.upload')),
            ],
            options={
                'verbose_name': 'Продажа SKU',
                'verbose_name_plural': 'Продажи по SKU (факт)',
            },
        ),
        migrations.CreateModel(
            name='DebtFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, null=True, verbose_name='Дата снимка')),
                ('client', models.CharField(db_index=True, max_length=255, verbose_name='Контрагент')),
                ('manager', models.CharField(blank=True, max_length=255, verbose_name='Менеджер')),
                ('ship_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('debt_total', models.BigIntegerField(default=0, verbose_name='Долг всего')),
                ('debt_overdue', models.BigIntegerField(default=0, verbose_name='Просрочено')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='Дней просрочки')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.upload')),
            ],
            options={
                'verbose_name': 'Дебиторка',
                'verbose_name_plural': 'Дебиторка (факт)',
            },
        ),
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('manager', models.CharField(blank=True, max_length=255, verbose_name='Менеджер')),
                ('amount', models.BigIntegerField(verbose_name='План, ₽ с НДС')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'План продаж',
                'verbose_name_plural': 'Планы продаж',
                'unique_together': {('year', 'month', 'manager')},
            },
        ),
        migrations.CreateModel(
            name='SalesFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Реализация', 'Реализация'), ('Корректировка', 'Корректировка'), ('Комиссионер', 'Отчёт комиссионера'), ('Прочее', 'Прочее')], default='Реализация', max_length=20)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(db_index=True, max_length=255, verbose_name='Контрагент')),
                ('manager', models.CharField(blank=True, max_length=255, verbose_name='Менеджер')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField()),
                ('qty', models.FloatField(default=0, verbose_name='Количество')),
                ('amount', models.BigIntegerField(default=0, verbose_name='Сумма с НДС')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.upload')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи (факт из 1С)',
                'indexes': [models.Index(fields=['year', 'month'], name='dashboard_s_year_333fc5_idx'), models.Index(fields=['client'], name='dashboard_s_client_546583_idx')],
            },
        ),
    ]
