# Generated by Django 5.2.16 on 2026-07-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upak', models.CharField(max_length=255, unique=True, verbose_name='Упаковка')),
                ('sku', models.CharField(db_index=True, max_length=255, verbose_name='Батончик (SKU для расхода)')),
                ('series', models.CharField(blank=True, max_length=40, verbose_name='Серия')),
                ('stock', models.BigIntegerField(default=0, verbose_name='Остаток')),
                ('is_active_manual', models.BooleanField(blank=True, help_text='Пусто = определяется автоматически по продажам', null=True, verbose_name='Используется (ручной флаг)')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Справочник упаковки',
                'ordering': ['series', 'upak'],
            },
        ),
    ]
