# Generated by Django 5.2.16 on 2026-07-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_packagingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(db_index=True, max_length=255, verbose_name='Контрагент')),
                ('ship_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('debt_total', models.BigIntegerField(default=0, verbose_name='Долг по документу')),
                ('debt_overdue', models.BigIntegerField(default=0, verbose_name='Просрочено')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='Дней просрочки')),
                ('bucket', models.CharField(blank=True, max_length=20, verbose_name='Корзина срока')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.upload')),
            ],
            options={
                'verbose_name': 'Реализация в долге',
                'verbose_name_plural': 'Дебиторка по реализациям',
                'indexes': [models.Index(fields=['client'], name='dashboard_d_client_2d5ecb_idx')],
            },
        ),
    ]
