# Generated by Django 5.2.16 on 2026-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_debtline'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtline',
            name='doc_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='Номер документа'),
        ),
    ]
