# Generated by Django 5.2.16 on 2026-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_debtline_doc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата снимка')),
                ('total', models.BigIntegerField(default=0, verbose_name='Долг всего')),
                ('overdue', models.BigIntegerField(default=0, verbose_name='Просрочено')),
                ('count', models.IntegerField(default=0, verbose_name='Должников')),
            ],
            options={
                'verbose_name': 'Снимок дебиторки',
                'verbose_name_plural': 'История дебиторки (снимки)',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='packagingitem',
            name='snap_key',
            field=models.CharField(blank=True, db_index=True, help_text='Нормализованное имя из файла-снимка для авто-обновления остатка', max_length=255, verbose_name='Ключ снимка'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='kind',
            field=models.CharField(choices=[('sales_client', 'Продажи по контрагентам'), ('sales_sku', 'Продажи по номенклатуре'), ('debt', 'Дебиторка'), ('packaging', 'Остатки упаковки')], max_length=20, verbose_name='Тип отчёта'),
        ),
        migrations.CreateModel(
            name='DebtClientSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата снимка')),
                ('client', models.CharField(db_index=True, max_length=255, verbose_name='Контрагент')),
                ('debt_total', models.BigIntegerField(default=0, verbose_name='Долг')),
                ('debt_overdue', models.BigIntegerField(default=0, verbose_name='Просрочено')),
            ],
            options={
                'verbose_name': 'Долг клиента (снимок)',
                'verbose_name_plural': 'История долга по клиентам',
                'unique_together': {('date', 'client')},
            },
        ),
    ]
