# Generated by Django 5.2.16 on 2026-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_debtsnapshot_packagingitem_snap_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=180, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=180, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Полное наименование'),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=15, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.CharField(blank=True, max_length=255, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='client',
            name='synced_at',
            field=models.DateField(blank=True, null=True, verbose_name='Актуализировано из 1С'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='kind',
            field=models.CharField(choices=[('sales_client', 'Продажи по контрагентам'), ('sales_sku', 'Продажи по номенклатуре'), ('debt', 'Дебиторка'), ('packaging', 'Остатки упаковки'), ('contractors', 'Справочник контрагентов')], max_length=20, verbose_name='Тип отчёта'),
        ),
    ]
