# Generated by Django 5.2.16 on 2026-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account',
            field=models.CharField(blank=True, max_length=40, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='client',
            name='bik',
            field=models.CharField(blank=True, max_length=15, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='client',
            name='contract',
            field=models.CharField(blank=True, max_length=200, verbose_name='Договор (№, дата, срок)'),
        ),
        migrations.AddField(
            model_name='client',
            name='delivery',
            field=models.CharField(blank=True, max_length=200, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='client',
            name='kpp',
            field=models.CharField(blank=True, max_length=15, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='client',
            name='min_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мин. заказ, ₽'),
        ),
        migrations.AddField(
            model_name='client',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=120, verbose_name='Оплата (предоплата / отсрочка N дней)'),
        ),
        migrations.AddField(
            model_name='client',
            name='retro_bonus',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ретро-бонус / особые условия'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('потенциальный', 'Потенциальный'), ('активный', 'Активный'), ('приостановлен', 'Приостановлен'), ('бывший', 'Бывший')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=180, verbose_name='Город / регион'),
        ),
    ]
