# Generated by Django 5.2.16 on 2026-07-28 07:04

from django.db import migrations, models


def stamp_existing(apps, schema_editor):
    """Проставить дату снимка уже загруженным строкам (все относятся к текущему снимку),
    чтобы после апдейта дебиторка/график не пропали до следующей загрузки."""
    DebtFact = apps.get_model('dashboard', 'DebtFact')
    DebtLine = apps.get_model('dashboard', 'DebtLine')
    from django.db.models import Max
    d = DebtFact.objects.aggregate(m=Max('snapshot_date'))['m']
    if d is None:
        from datetime import date
        d = date.today()
        DebtFact.objects.filter(snapshot_date__isnull=True).update(snapshot_date=d)
    DebtLine.objects.filter(snapshot_date__isnull=True).update(snapshot_date=d)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_client_account_client_bank_client_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtline',
            name='snapshot_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата снимка'),
        ),
        migrations.RunPython(stamp_existing, migrations.RunPython.noop),
    ]
