# Generated by Django 5.2.16 on 2026-07-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_debtline_snapshot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(blank=True, max_length=100, verbose_name='Линейка')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Позиция (из файла себестоимости)')),
                ('cost', models.FloatField(verbose_name='Себестоимость без НДС, ₽')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='SKU для цены продажи (карточка 1С)')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Себестоимость',
                'verbose_name_plural': 'Себестоимость (справочник)',
                'ordering': ['line', 'name'],
            },
        ),
    ]
