# Generated by Django 5.2.16 on 2026-07-29 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_costitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=255, verbose_name='SKU (карточка 1С)')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='dashboard.costitem', verbose_name='Позиция себестоимости')),
            ],
            options={
                'verbose_name': 'SKU позиции',
                'verbose_name_plural': 'SKU позиций себестоимости',
                'unique_together': {('cost', 'sku')},
            },
        ),
    ]
