# Generated by Django 5.2.16 on 2026-07-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_costsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfact',
            name='doc_no',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Номер документа'),
        ),
        migrations.CreateModel(
            name='SkuDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(db_index=True, max_length=60, verbose_name='Номер документа')),
                ('sku_raw', models.CharField(db_index=True, max_length=255, verbose_name='Карточка 1С')),
                ('year', models.IntegerField(db_index=True)),
                ('qty', models.FloatField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.upload')),
            ],
            options={
                'verbose_name': 'Реализация SKU',
                'verbose_name_plural': 'Реализации по SKU (для сшивки с клиентом)',
            },
        ),
    ]
