# Generated by Django 5.2.16 on 2026-07-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_salesfact_doc_no_skudoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название группы')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('items', models.ManyToManyField(blank=True, related_name='groups', to='dashboard.costitem', verbose_name='Позиции себестоимости в группе')),
            ],
            options={
                'verbose_name': 'Группа себестоимости',
                'verbose_name_plural': 'Группы себестоимости (свои)',
                'ordering': ['order', 'name'],
            },
        ),
    ]
