# Generated by Django 5.2.16 on 2026-07-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_costgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='costgroup',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='cost_groups', to='dashboard.client', verbose_name='Контрагенты (считать по их реальным покупкам)'),
        ),
        migrations.AlterField(
            model_name='costgroup',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='groups', to='dashboard.costitem', verbose_name='Позиции себестоимости (ручной список)'),
        ),
    ]
