# Generated by Django 5.2.16 on 2026-08-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_costgroup_clients_alter_costgroup_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=255, verbose_name='Компания')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='ИНН')),
                ('channel', models.CharField(blank=True, choices=[('сети', 'Сетевой ритейл'), ('зож', 'ЗОЖ-розница'), ('e-com', 'E-com / маркетплейс'), ('horeca', 'HoReCa'), ('опт', 'Опт / дистрибуция'), ('стм', 'СТМ / контракт'), ('прочее', 'Прочее')], max_length=20, verbose_name='Канал')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('contact', models.CharField(blank=True, max_length=160, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=160, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='Сайт')),
                ('source', models.CharField(blank=True, help_text='Где нашли: веб-поиск, выставка, рекомендация…', max_length=160, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('contacted', 'Написали'), ('replied', 'Ответил'), ('negotiation', 'Переговоры'), ('won', 'Стал клиентом'), ('lost', 'Отказ')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('owner', models.CharField(blank=True, max_length=160, verbose_name='Ответственный')),
                ('note', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('last_touch', models.DateField(blank=True, null=True, verbose_name='Последний контакт')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды (потенциальные клиенты)',
                'ordering': ['-updated_at'],
            },
        ),
    ]
