# Generated by Django 5.2.16 on 2026-08-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='potential',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Потенциал сделки, ₽'),
        ),
    ]
