# Generated by Django 5.2.16 on 2026-08-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_lead_potential'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название этапа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_won', models.BooleanField(default=False, verbose_name='Успех (стал клиентом)')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Отказ')),
            ],
            options={
                'verbose_name': 'Этап воронки',
                'verbose_name_plural': 'Этапы воронки (лиды)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='dashboard.leadstage', verbose_name='Этап'),
        ),
    ]
