# Generated by Django 5.2.16 on 2026-08-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_seed_lead_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted',
            field=models.BooleanField(default=False, verbose_name='Заведён клиентом'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.DateField(blank=True, null=True, verbose_name='Следующий шаг (дата)'),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='color',
            field=models.CharField(default='#6d5bd0', max_length=9, verbose_name='Цвет'),
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.lead')),
            ],
            options={
                'verbose_name': 'История лида',
                'verbose_name_plural': 'История лидов',
                'ordering': ['-created_at'],
            },
        ),
    ]
