# Generated by Django 5.2.16 on 2026-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_stage_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='socials',
            field=models.TextField(blank=True, help_text='Ссылки на соцсети, по одной в строке или через запятую', verbose_name='Соцсети (ссылки)'),
        ),
    ]
