# Generated by Django 5.2.16 on 2026-08-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_seed_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='can_edit_all',
            field=models.BooleanField(default=False, verbose_name='Может редактировать всех клиентов'),
        ),
    ]
