# Generated by Django 5.2.16 on 2026-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_managerprofile_can_edit_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('user', models.CharField(blank=True, max_length=120, verbose_name='Кто')),
                ('action', models.CharField(max_length=40, verbose_name='Действие')),
                ('lead_id', models.IntegerField(blank=True, null=True, verbose_name='ID лида')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('detail', models.TextField(blank=True, verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Лог лида',
                'verbose_name_plural': 'Логи лидов (аудит)',
                'ordering': ['-created_at'],
            },
        ),
    ]
