# Generated by Django 5.2.16 on 2026-08-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_leadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfact',
            name='schet_no',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Номер счёта на оплату'),
        ),
    ]
