# Generated by Django 5.2.16 on 2026-08-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_salesfact_schet_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Себестоимость без НДС, ₽')),
                ('effective_from', models.DateField(auto_now_add=True, db_index=True, verbose_name='Действует с')),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.costitem')),
            ],
            options={
                'verbose_name': 'История себестоимости',
                'verbose_name_plural': 'История себестоимости',
                'ordering': ['-effective_from', '-id'],
            },
        ),
    ]
