# Generated by Django 5.2.16 on 2026-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_costhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfact',
            name='base_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60, verbose_name='Основание (реализация) для корректировки'),
        ),
    ]
