# Generated by Django 5.2.16 on 2026-09-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_salesfact_base_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#6d5bd0', max_length=9, verbose_name='Цвет')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'В архиве')], default='active', max_length=10, verbose_name='Статус')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('todo', 'Надо сделать'), ('doing', 'В работе'), ('review', 'На проверке'), ('done', 'Готово')], db_index=True, default='todo', max_length=10, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('med', 'Средний'), ('high', 'Высокий')], default='med', max_length=6, verbose_name='Приоритет')),
                ('assignee', models.CharField(blank=True, max_length=160, verbose_name='Исполнитель')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('client', models.CharField(blank=True, max_length=255, verbose_name='Клиент (привязка)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('done_at', models.DateField(blank=True, null=True, verbose_name='Выполнена')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.lead', verbose_name='Лид (привязка)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи (трекер)',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
