# Generated by Django 5.2.16 on 2026-09-01 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_project_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название этапа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('color', models.CharField(default='#6d5bd0', max_length=9, verbose_name='Цвет')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено (для прогресса)')),
            ],
            options={
                'verbose_name': 'Этап задач',
                'verbose_name_plural': 'Этапы задач',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='dashboard.salesmanager', verbose_name='Исполнители'),
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.taskstage', verbose_name='Этап'),
        ),
    ]
