# Generated by Django 5.2.16 on 2026-09-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_seed_task_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав / детали'),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(blank=True, max_length=160, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/%Y/%m/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('uploaded_by', models.CharField(blank=True, max_length=120, verbose_name='Загрузил')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.project')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.project')),
            ],
            options={
                'verbose_name': 'Комментарий проекта',
                'verbose_name_plural': 'Комментарии проектов',
                'ordering': ['-created_at'],
            },
        ),
    ]
