from django.contrib import admin
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from dashboard import views, api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.svodka, name='svodka'),
    path('prodazhi/', views.prodazhi, name='prodazhi'),
    path('debitorka/', views.debitorka, name='debitorka'),
    path('oplaty/', views.oplaty, name='oplaty'),
    path('oplaty/day/<day>/', views.oplaty_day, name='oplaty_day'),
    path('signals/', views.signals, name='signals'),
    path('cost/', views.cost, name='cost'),
    path('cost/map/', views.cost_map, name='cost_map'),
    path('cost/channel/<code>/', views.cost_channel, name='cost_channel'),
    path('rfm/', views.rfm, name='rfm'),
    path('export/', views.export_xlsx, name='export'),
    path('managers/', views.managers, name='managers'),
    path('managers/<path:manager>/', views.manager_card, name='manager_card'),
    path('sravnenie/', views.sravnenie, name='sravnenie'),
    path('sravnenie/sku/', views.sravnenie_sku, name='sravnenie_sku'),
    path('sravnenie/clients/', views.sravnenie_clients, name='sravnenie_clients'),
    path('sravnenie/drill/', views.sravnenie_drill, name='sravnenie_drill'),
    path('clients/', views.clients, name='clients'),
    path('leads/', views.leads, name='leads'),
    path('leads/list/', views.leads_list, name='leads_list'),
    path('leads/stages/', views.lead_stages, name='lead_stages'),
    path('leads/logs/', views.lead_logs, name='lead_logs'),
    path('leads/import/', views.lead_import, name='lead_import'),
    path('leads/<int:lead_id>/move/', views.lead_move, name='lead_move'),
    path('leads/<int:lead_id>/delete/', views.lead_delete, name='lead_delete'),
    path('leads/<int:lead_id>/quick/', views.lead_quick, name='lead_quick'),
    path('leads/<int:lead_id>/', views.lead_card, name='lead_card'),
    path('clients/<path:client>/', views.client_card, name='client_card'),
    path('upakovka/', views.upakovka, name='upakovka'),
    path('debitorka/<path:client>/', views.debtor, name='debtor'),
    path('upload/', views.upload, name='upload'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('tg/<secret>/webhook/', csrf_exempt(views.tg_webhook), name='tg_webhook'),
    path('doc/<kind>/<path:number>/', views.doc_download, name='doc_download'),
    # ---- Read-only JSON API для внешних ИИ (ChatGPT Actions / Claude) ----
    path('api/v1/openapi.json', api.openapi),
    path('api/v1/health', api.health),
    path('api/v1/overview', api.overview),
    path('api/v1/sales', api.sales),
    path('api/v1/top-clients', api.top_clients),
    path('api/v1/managers', api.managers),
    path('api/v1/top-sku', api.top_sku),
    path('api/v1/debtors', api.debtors),
    path('api/v1/margin', api.margin),
    path('api/v1/client', api.client),
    path('api/v1/signals', api.signals),
]
